const BlockArray = [
  {
    timeString: "2023/10/24 10:32PM",
    locationString: "USA, Walnut Creek",
    feelsString: "- - - - - - - -",
    energyString: "* * * * * *",
    hoursSleptString: "* * * * * ",
    extrasString: "[X][O][O][X][O]",
    borderColor: "#f51777",
  },
  {
    timeString: "2023/10/24 10:32PM",
    locationString: "USA, Walnut Creek",
    feelsString: "- - - - - - - -",
    energyString: "* * * * * *",
    hoursSleptString: "* * * * * ",
    extrasString: "[X][O][O][X][O]",
    borderColor: "purple",
  },
  {
    timeString: "2023/10/24 10:32PM",
    locationString: "USA, Walnut Creek",
    feelsString: "- - - - - - - -",
    energyString: "* * * * * *",
    hoursSleptString: "* * * * * ",
    extrasString: "[X][O][O][X][O]",
    borderColor: "#f51777",
  },
  {
    timeString: "2023/10/24 10:32PM",
    locationString: "USA, Walnut Creek",
    feelsString: "- - - - - - - -",
    energyString: "* * * * * *",
    hoursSleptString: "* * * * * ",
    extrasString: "[X][O][O][X][O]",
    borderColor: "blue",
  },
  {
    timeString: "2023/10/24 10:32PM",
    locationString: "USA, Walnut Creek",
    feelsString: "- - - - - - - -",
    energyString: "* * * * * *",
    hoursSleptString: "* * * * * ",
    extrasString: "[X][O][O][X][O]",
    borderColor: "#f51777",
  },
  {
    timeString: "2023/10/24 10:32PM",
    locationString: "USA, Walnut Creek",
    feelsString: "- - - - - - - -",
    energyString: "* * * * * *",
    hoursSleptString: "* * * * * ",
    extrasString: "[X][O][O][X][O]",
    borderColor: "yellow",
  },
  {
    timeString: "2023/10/24 10:32PM",
    locationString: "USA, Walnut Creek",
    feelsString: "- - - - - - - -",
    energyString: "* * * * * *",
    hoursSleptString: "* * * * * ",
    extrasString: "[X][O][O][X][O]",
    borderColor: "#f51777",
  },
];

export default BlockArray;
